#!/bin/bash
# This scripot waits for a shutdown signal and then sets the wakeup to be 7am


trap shutdownStuff SIGTERM

function shutdownStuff() {
  pmset -a womp 1 disksleep 3 displaysleep 15 autorestart 1 sleep 15 2> /dev/null
  pmset repeat wakeorpoweron MTWRFSU 07:00:00
}

# Wait for the shutdown
[ ! -e /tmp/mypipe ] && mkfifo /tmp/mypipe
while read SIGNAL; do
  :
done < /tmp/mypipe
