#!/bin/bash
# pmset script

if [ $(id -u) = "0" ]; then
echo
else
echo "Must be run as root..."
exit 1
fi

# Reset our go-to-sleep pmset prefs
#
# womp 1 == wake on magic packet
# displaysleep 0 == Don't waste effort trying to dim the display
# sleep 30 == sleep the system after 30 minutes of idle
# disksleep 3 == spin down HD after idle period
# autorestart 1 == restart after AC outage

pmset -a womp 1 disksleep 3 displaysleep 0 autorestart 1 sleep 30 2> /dev/null

hour=`date +"%H"`
let hour+=8

pmset repeat wakeorpoweron MTWRFSU $hour:00:00 shutdown MTWRFSU 00:10:00

exit
